databases:
  - name: schweinsteiger_db
    plan: free

services:
  - type: web
    name: django_api
    runtime: docker
    repo: https://github.com/yachaab/Djangres
    plan: free
    env: python
    buildCommand: docker build -t django_api .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: schweinsteiger_db
          property: connectionString
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        value: ${DJANGO_ALLOWED_HOSTS}
      - key: PORT
        value: "8000"
